baseURL: https://neweb.whitmanarchives.org
languageCode: en-us
defaultContentLanguage: en
title: Penrose Library
theme: Penrose-cupper-hugo-theme
googleAnalytics: 
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/
  pages: /:filename/

imaging:
  quality: 99

params:
  description: Penrose Library NxtGen website. Under Deveopment. Do not use.
  homeMetaContent: Penrose Library NG website. Deveopment. Do not use
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to Cloudflare Page.
  # For more date formats see https://gohugo.io/functions/format/
  MatomoSiteID: 1
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  moveFooterToHeader: false
  customCss:
 #   - css/bootstrap.min.css
    - css/simple-tooltip.css
    - css/custom.css
  customJs:
    - js/jquery-3.6.0.min.js
  #  - js/bootstrap.min.js
    - js/home-searchbox.js
    - js/van11y-accessible-simple-tooltip-aria.min.js

menu:
  nav:
    - name: Database A-Z
      url: https://libguides.whitman.edu/az.php
      weight: 1
    - name: Lib
      url: https://libguides.whitman.edu/?b=s
      weight: 2
    - name: Blog
      url: /post/
      weight: 3
    - name: Library Services
      url: /libraryservices/
      weight: 4
    - name: Faculty Services
	    url: /faculty_services/
	    weight: 5
    - name: About the Library
      url: /about_the_library/
      weight: 6


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
