baseURL: https://penrose.whitman.edu
languageCode: en-us
defaultContentLanguage: en
title: Penrose Library, Whitman College, Walla Walla, WA
theme: Penrose-cupper-hugo-theme
googleAnalytics: 
disqusShortname: 
enableGitInfo: true
summaryLength: 25

taxonomies:
  tag: tags

permalinks:
  post: /blog/:filename/
  pages: /:filename/

imaging:
  quality: 99

params:
  description: 
  homeMetaContent: Penrose Library NG website. Deveopment. Do not use
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to Cloudflare Page.
  # For more date formats see https://gohugo.io/functions/format/
  MatomoSiteID: 1
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: false
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  moveFooterToHeader: false
  customCss:
    - css/simple-tooltip.css
    - css/custom.css
  customJs:
   - js/jquery-3.6.0.min.js
    - js/home-searchbox.js
    - js/custom.js
    - js/van11y-accessible-simple-tooltip-aria.min.js

menu:
  nav:
    - name: Database A-Z
      url: /A_Z_list/
      weight: 1
    - name: Library Guides
      url: https://libguides.whitman.edu/?b=s
      weight: 3
    - name: FAQ & Services
      url: /libraryservices/
      weight: 7
    - name: Contact Librarians
      url: /contact_librarian/
      weight: 6       
    - name: Faculty Services
      url: /faculty_services/
      weight: 13
    - name: About the Library
      url: /about_the_library/
      weight: 25
    - name: ARMINDA
      url: https://arminda.whitman.edu
      weight: 23
    - name: Course Reserves
      url: /course-reserves
      weight: 19
    - name: Archives
      url: /archives
      weight: 5
    - name: Thesis
      url: /thesis
      weight: 21
    - name: Blog
      url: /blog
      weight: 27


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false

  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
